sudo: required
dist: xenial

language: node_js
node_js: 14

cache:
  directories:
    - $HOME/haxe

os:
  - linux
  # - osx

env:
  - HAXE_VERSION=3.4.7
  - HAXE_VERSION=4.0.5
  - HAXE_VERSION=4.1.5
  - HAXE_VERSION=4.2.4
  - HAXE_VERSION=nightly
  
install:
  - npm i -g lix
  - lix install haxe $HAXE_VERSION
  - lix download
  
script:
  # - lix run travix interp
  # - lix run travix neko
  # - lix run travix python
  - lix run travix node
  # - lix run travix flash
  # - lix run travix java
  # - lix run travix cs
  - lix run travix js
  # - lix run travix cpp
  # - lix run travix php
